vim.g.mapleader = " "

local options = {
    pumheight = 7,
    rnu = true,
    hidden = true,
    nu = true,
    showcmd = false,
    ruler = false,
    lazyredraw = true,
    synmaxcol = 2048,
    completeopt = { "menuone", "noselect" },
    expandtab = true,
    autoindent = true,
    smartindent = true,
    cindent = true,
    shiftwidth = 4,
    softtabstop = 4,
    tabstop = 8,
    wrap = false,
    ignorecase = true,
    smartcase = true,
    mouse = "a",
    splitright = true,
    splitbelow = true,
    timeout = true,
    timeoutlen = 200,
    ttimeout = true,
    ttimeoutlen = 1,
    ttyfast = true,
    updatetime = 100,
    redrawtime = 1500,
    scrolloff = 8,
    cmdheight = 0,
    undofile = true,
    undolevels = 5000,
    writebackup = false,
    swapfile = false,
    fileformat = "unix",
    encoding = "utf-8",
    showtabline = 2,
    laststatus = 3,
    termguicolors = true,
    mousemoveevent = true,
    cursorline = true,
    cursorlineopt = "number",
    showmode = false,
    spell = false,
    spl = { "fr", "en_us" },
}

for k, v in pairs(options) do
    vim.opt[k] = v
end

vim.opt.shortmess = {
    t = true,
    A = true,
    o = true,
    O = true,
    T = true,
    f = true,
    F = true,
    s = true,
    c = true,
    W = true,
}

vim.opt.formatoptions = {
    ['1'] = true,
    ['2'] = true,
    q = true,
    c = true,
    r = true,
    n = true,
    t = false,
    j = true,
    l = true,
    v = true,
}
